import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
await page.goto("http://localhost:3000/signup?next=%2Fapply%2Fresume", { waitUntil: "networkidle" });
await page.waitForTimeout(1200);
await page.screenshot({ path: ".scratch/signup-desktop.png" });
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForTimeout(600);
await page.screenshot({ path: ".scratch/signup-mobile.png" });
await browser.close();
