export const INVITATION_GENERATION_MAX_COUNT = 100_000;
export const INVITATION_GENERATION_DEFAULT_EXPIRED_DAYS = 90;
export const INVITATION_GENERATION_MAX_EXPIRED_DAYS = 3650;
export const INVITATION_GENERATION_MAX_EXPIRED_HOURS = 23;
export const INVITATION_GENERATION_MAX_EXPIRED_MINUTES = 59;
