export const INVITATION_GENERATION_MAX_COUNT = 1_000_000;
export const INVITATION_GENERATION_PREVIEW_LIMIT = 8;
/** Rows per createMany call. Keep under Postgres bind-variable limits (~65k). */
export const INVITATION_GENERATION_INSERT_CHUNK_SIZE = 2_000;
export const INVITATION_GENERATION_DEFAULT_EXPIRED_DAYS = 90;
export const INVITATION_GENERATION_MAX_EXPIRED_DAYS = 3650;
export const INVITATION_GENERATION_MAX_EXPIRED_HOURS = 23;
export const INVITATION_GENERATION_MAX_EXPIRED_MINUTES = 59;
